### ISSUE TITLE
Collapsible rows

### ISSUE THREAD

**Issue by iafisher** [elpez/byte-me#23]
See [this fiddle](https://jsfiddle.net/4cLLt6sy/) for details.

**Comment by elpez** [comment]
I'm going to keep this open until we fix these quirks:

- The uncollapsing is instantaneous and the recollapsing pauses for a second; these should both be smooth.
- There should be an arrow or something to indicate whether the row has been collapsed or not, because right now it just looks like every line of source code has a single bytecode instruction.
